# Generated by Django 5.2.1 on 2025-06-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myWalletapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
